---
title: "stability"
author: "Jeffrey Cheng"
date: "2022-12-06"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyverse)

source("./routines.R")
```



## Lasso  Feature Selection and Cross Validation

```{r}
av <- read.csv("./CSpine/CSV datasets/analysisvariables.csv")

vars <- colnames(av)[5:ncol(av)]

# remove testing data
data_train <- av %>% filter(SITE != 5 & SITE != 16 & SITE != 15)

y <- unlist(lapply(data_train$ControlType, function(x){
  if (x == "case")
    {return (1)} 
  else 0}))

data_train$y <- y


dat_no_na <- data_train[rowSums(is.na(data_train)) == 0, ]

```

```{r}
# get baseline deicsion rule results 
avnn_reprod <-  as.numeric(dat_no_na$AlteredMentalStatus == 1 |  dat_no_na$FocalNeuroFindings == 1 | 
                            dat_no_na$PainNeck == 1 | dat_no_na$SubInj_TorsoTrunk == 1 | dat_no_na$Predisposed == 1 |
                            dat_no_na$HighriskDiving == 1 | dat_no_na$HighriskHitByCar == 1 | 
                            dat_no_na$HighriskMVC == 1 |   dat_no_na$axialloadtop == 1 | dat_no_na$Clotheslining == 1)

avnn_reprod2 <- as.numeric(dat_no_na$AlteredMentalStatus == 1 | dat_no_na$FocalNeuroFindings == 1 |  
                            dat_no_na$PainNeck == 1| dat_no_na$SubInj_TorsoTrunk == 1 | 
                            dat_no_na$HighriskDiving == 1 |dat_no_na$HighriskMVC == 1)
```



## Feature Selection - Bootstrap

```{r}

# Setting alpha = 1 implements lasso regression
X <- dat_no_na[, vars]

# find value of lambda that minimizes the deviance
lasso_reg <- glmnet::cv.glmnet(as.matrix(X),  y = dat_no_na$y, alpha = 1, standardize = TRUE, nfolds = 14)

lambda_best <- lasso_reg$lambda.min

# get lasso model with optimal performance found with cross validation

lasso_model <- glmnet(x = X, y = dat_no_na$y, alpha = 1, standardize = TRUE)

ord <- lasso_model$beta

sum_0 <- apply(ord, MARGIN = 1, function(r){
  return(sum(r == 0))
})

# get features in the order they are added to the model
sorted_sum <- data.frame(sort(sum_0))

selected_names <- rownames(sorted_sum)[1:16]
```

## Data Perturbation - Bootstrap

```{r}
library(ggplot2)

selected_names_counts = integer(length(selected_names))

sens_low = c()
sens_high = c()
sens = c()

spec_low = c()
spec_high = c()
spec = c()

# do n_bootstraps bootstraps (sample with replacement)
set.seed(1)
n_bootstraps = 100
for (i in 1:n_bootstraps){
  # resample from data_train
  data_train_boot <- data_train[sample(nrow(data_train),size=nrow(data_train),replace=TRUE),]
  y <- unlist(lapply(data_train_boot$ControlType, function(x){
  if (x == "case")
    {return (1)} 
  else 0}))

  data_train_boot$y <- y
  
  
  dat_no_na <- data_train_boot[rowSums(is.na(data_train_boot)) == 0, ]
  X <- dat_no_na[, vars]

  # find value of lambda that minimizes the deviance
  lasso_reg <- glmnet::cv.glmnet(as.matrix(X),  y = dat_no_na$y, alpha = 1, standardize = TRUE, nfolds = 14)
  
  lambda_best <- lasso_reg$lambda.min
  
  # get lasso model with optimal performance found with cross validation
  
  lasso_model <- glmnet(x = X, y = dat_no_na$y, alpha = 1, standardize = TRUE)
  
  ord <- lasso_model$beta
  
  sum_0 <- apply(ord, MARGIN = 1, function(r){
    return(sum(r == 0))
  })
  
  # get features in the order they are added to the model
  sorted_sum <- data.frame(sort(sum_0))
  
  bootstrapped_names <- rownames(sorted_sum)[1:16]
   
  for (j in 1:length(selected_names)){
    if (selected_names[j] %in% bootstrapped_names){
      selected_names_counts[j] <- selected_names_counts[j] + 1
    }
  }
  selected_names_freq <- selected_names_counts/n_bootstraps
  
  
  num_preds <- rep(0, nrow(dat_no_na))
  class_preds <- rep(0, nrow(dat_no_na))
  
  for (i in unique(dat_no_na$SITE)){
    train <-  dat_no_na[dat_no_na$SITE!=i,]
    test <-  dat_no_na[dat_no_na$SITE==i,]
    
    X <- train[, vars]
    X_test <- test[, vars]
    
    lasso_model <- glmnet(x = X, y = train$y, alpha = 1, lambda = lambda_best, standardize = TRUE)
    
    num_preds[dat_no_na$SITE==i] <-  predict(lasso_model, type = "response", newx = as.matrix(X_test))
    
  }
  
  class_preds <- as.numeric(num_preds > 0.085)

  
  class_preds <- as.numeric(num_preds > 0.085)
  results <- metrics(dat_no_na$ControlType == "case", class_preds)
  
  sens = c(sens, results[1,1])
  sens_low = c(sens_low, results[1,2])
  sens_high = c(sens_high, results[1,3])
  
  spec = c(spec, results[2,1])
  spec_low = c(spec_low, results[2,2])
  spec_high = c(spec_high, results[2,3])
  

  
}
names(selected_names_freq) <- selected_names

barplot(selected_names_freq, 
        main = "Frequency of Selected Features During Bootstrapping", 
        xlab = 'Feature', ylab = 'Frequency', las = 2, cex.names = 0.5)

CI_bootstrap_sens <-round(data.frame(x = 1:n_bootstraps,
                                     sens = sens,
                                     sens_low = sens_low,
                                     sens_high = sens_high), 4)
  
# Creating scatter plot with its
# confindence intervals
ggplot(CI_bootstrap_sens, aes(x, sens)) + geom_point() + 
geom_errorbar(aes(ymin = sens_low, ymax = sens_high))+ xlab('Sample') + 
ylab('Sensitivity Estimate') + ggtitle('Sensitivity Estimates Across Bootstraps')

CI_bootstrap_spec <-round(data.frame(x = 1:n_bootstraps,
                                     spec = spec,
                                     spec_low = spec_low,
                                     spec_high = spec_high), 4)
  
# Creating scatter plot with its
# confindence intervals
ggplot(CI_bootstrap_spec, aes(x, spec)) + geom_point() + 
geom_errorbar(aes(ymin = spec_low, ymax = spec_high)) + xlab('Sample') +
ylab('Specificity Estimate') + ggtitle('Specificity Estimates Across Bootstraps')

```

